### ISSUE TITLE
Hi Again, I can't find the github commands on the extension

### ISSUE THREAD

**Issue by vini765** [fxnoob/voice-typing-chrome-extension#3]
There are only 6 commands in the extension, can you teach me how to activate the other commands? Sorry if this is a dumb question, I don't understand programming at all but I love your extension, thanks for the project.

calculate: say calculate 'expression' to calculate to math. eg. 'calculate five times fifteen' to calculate 5*15

scroll down: Say 'scroll down' to scroll down the current page.

scroll up: Say 'scroll up' to scroll up the current page.

scroll top: Say 'scroll top' to scroll to top on the current page.

next: Say 'next' to navigate to next element(mimics tab navigation).

previous: Say 'previous' to navigate to previous element (mimics tab navigation).

undo all: Say 'undo all' to undo everything on current page upto 20 depth.

Arrow: Say 'Arrow left' to type left arrow key. (play 2048 game with your voice on https://play2048.co/ by saying arrow left , arrow right, arrow up, arrow down).

Go to: Say 'Go to facebook.com' to open new tab for facebook.com

Go to bookmark #bookmark_search_term: Open matched bookmark search url.

Remind me: Say 'Remind me in 9 minutes' to set a reminder for 10 minutes.

search: Say 'search cat' to search cat on google or on youtube

bookmark: Say 'Bookmark this page' or 'remove bookmark' to add or remove bookmark or Say go to bookmark bookmark_name to open matched bookmark url

Play: Say 'Play song_name' to play the song from youtube.

**Comment by fxnoob** [comment]
@vini765  my bad. commands list link is outdated. i will update it. Currently available commands are listed in chrome extension already.

This project is the successor of my old project https://github.com/fxnoob/speech-recognition-toolkit. if you build that extension locally and load it locally, you will get all the commands you mentioned.

**Comment by vini765** [comment]
thank you, I sent a message on your discord!
